### ISSUE TITLE
Create a replacement for the old <dnn:DnnPageDropDownList /> webforms control

### ISSUE THREAD

**Issue by X3Technology** [DNNCommunity/dnn-elements#539]
This functionality is very useful for Dnn module developers that need to be able to select a Dnn page.

**Comment by valadas** [comment]
We now have dnn-select which can be used for dropdowns. Because these are just webcomponents we don't want to couple them too tight with existing rest APIs so they are more reusable and easier to maintain. But in a module one could now do a .map over the received json and populate the dropdown with those values.
